config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    get 'sign_in', to: redirect('/users/auth/google_oauth2'), as: :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  # authenticate :user do
    resources :csv_import, only: [:index, :create]
    resources :records, only: :index
  # end

  root 'static#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/external_record.rb
class ExternalRecord < ApplicationRecord
  has_many :guesses  
end

app/models/guess.rb
class Guess < ApplicationRecord
  belongs_to :internal_record
  belongs_to :external_record
end

app/models/internal_record.rb
class InternalRecord < ApplicationRecord
  has_many :guesses

  validates_presence_of :external_reference_number,
                        :negotiatus_reference_number,
                        :delivery_address_string,
                        :delivery_address_zipcode,
                        :amount_cents,
                        :date
end

app/models/record_filter.rb
class RecordFilter
  attr_reader :filter_start_date,
              :filter_end_date,
              :filter_match_status,
              :filter_payment_status,
              :filter_payable_status

  def initialize(scope:, params: {})
    @scope = scope

    @filter_start_date = params.fetch(:filter_start_date, nil)
    @filter_end_date = params.fetch(:filter_end_date, nil)

    @filter_match_status = params.fetch(:filter_match_status, nil)

    @filter_payment_status = params.fetch(:filter_payment_status, nil)
    @filter_payable_status = params.fetch(:filter_payable_status, nil)
  end

  def records
    @scope = scope_by_start_date if filter_start_date.present?
    @scope = scope_by_end_date if filter_end_date.present?

    @scope = scope_by_match_status if filter_match_status.present?

    @scope = scope_by_payment_status if filter_payment_status.present?
    @scope = scope_by_payable_status if filter_payable_status.present?

    @scope
  end

  private

  def scope_by_start_date
    @scope.where('date >= ?', Date.parse(filter_start_date))
  end

  def scope_by_end_date
    @scope.where('date <= ?', Date.parse(filter_end_date))
  end

  def scope_by_match_status
    case filter_match_status
    when STATUS_UNMATCHED
      @scope.where(reconciliation_id: nil)
    when STATUS_MATCHED
      @scope.where.not(reconciliation_id: nil)
    end
  end

  def scope_by_payment_status
    case filter_payment_status
    when STATUS_UNPAID
      @scope.where(paid_at: nil)
    when STATUS_PAID
      @scope.where.not(paid_at: nil)
    end
  end

  def scope_by_payable_status
    case filter_payable_status
    when STATUS_UNPAYABLE
      @scope.where(payable: false)
    when STATUS_PAYABLE
      @scope.where(payable: true)
    end
  end

  STATUS_UNMATCHED = 'unmatched'.freeze
  STATUS_MATCHED = 'matched'.freeze

  STATUS_UNPAID = 'unpaid'.freeze
  STATUS_PAID = 'paid'.freeze

  STATUS_UNPAYABLE = 'unpayable'.freeze
  STATUS_PAYABLE = 'payable'.freeze
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                  :integer          not null, primary key
#  first_name          :string           not null
#  last_name           :string           not null
#  provider            :string           not null
#  uid                 :string           not null
#  image               :string
#  email               :string           not null
#  remember_created_at :datetime
#  sign_in_count       :integer          default(0), not null
#  current_sign_in_at  :datetime
#  last_sign_in_at     :datetime
#  current_sign_in_ip  :inet
#  last_sign_in_ip     :inet
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class User < ApplicationRecord
  devise :registerable, :rememberable, :trackable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :validations

  def self.from_omniauth(access_token)
    where(
      provider: access_token.provider,
      uid:      access_token.uid
    ).first_or_create! do |user|
      if !(access_token.info.email =~ /@negotiatus.com$/)
        raise User::InvalidDomainError, "Must be a Negotiatus employee"
      end

      user.email      = access_token.info.email
      user.first_name = access_token.info.first_name
      user.last_name  = access_token.info.last_name
      user.image      = access_token.info.image
    end
  end

  def name
    "#{first_name} #{last_name[0]}."
  end

  def encrypted_password
    false
  end

  class InvalidDomainError < StandardError
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/csv_import_controller.rb
class CsvImportController < ApplicationController
  DISCREPANCY_DAYS = 15

  def index
  end

  def create
    result = CsvImportService.import(vendor: csv_import_params[:vendor], csv: csv_import_params[:file].tempfile)

    internal_records = InternalRecordImportService.get_request(
      vendor_name: csv_import_params[:vendor],
      start_date:  result[:start_date] - DISCREPANCY_DAYS.days,
      end_date:    result[:start_date] - DISCREPANCY_DAYS.days
    )

    result[:imported_ids].each do |id|
      RecordMatcherService.match(external_record_id: id)
    end

    message = "Imported #{result[:import_count]} records from external CSV<br>and #{internal_records} corresponding records from Negotiatus"

    if !result[:errors]
      flash[:success] = "Success: #{message}"
    else
      flash[:error] = "Found external records with disagreeing values:<br>#{result[:errors].join("<br>")}<br>#{message}"
    end

    redirect_to csv_import_index_path
  end

  private
    def csv_import_params
      params.permit(:vendor, :file)
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  rescue User::InvalidDomainError => e
    flash[:error] = e.message
    redirect_to root_path
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  def index
    @external_records = RecordFilter.new(
      scope: ExternalRecord.all,
      params: params.permit(
        :filter_start_date,
        :filter_end_date
      )
    ).records
  end

  private

  def filter_by_date

  end

  def filter_by_match_status

  end

  def filter_by_paid_status

  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
    if user_signed_in?
      redirect_to #somewhere
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    "notification " << case level.to_sym
                       when :primary then "is-primary"
                       when :info    then "is-info"
                       when :success then "is-success"
                       when :warning then "is-warning"
                       when :danger  then "is-danger"
                       else ""
                       end
  end
end

app/views/csv_import/index.html.erb
<div class="section">
  <div class="card section">
    Import a new invoice CSV
    <%= form_tag csv_import_index_path, method: :post, multipart: true do %>
      <div class="field">
        <%= label_tag :vendor, "Select a vendor", class: "label" %>
        <div class="control">
          <%= select_tag :vendor, options_for_select(["WB Mason"], "WB Mason"), class: "select" %>
        </div>
      </div>
      <div class="file field is_primary">
        <label class="file-label">
          <%= file_field_tag :file, accept: 'text/csv', class: "file-input" %>
          <span class="file-cta">
            <span class="file-icon">
              <i class="fa fa-upload"></i>
            </span>
            <span class="file-label">
              Choose a file…
            </span>
          </span>
          <span class="file-name">
            No file chosen
          </span>
        </label>
      </div>
      <div class="field">
        <%= submit_tag "Upload CSV", class: "button" %>
      </div>
    <% end %>
  </div>
</div>

<script>
$(function() {
  $("#file").change(function() {
    var file = $("#file")[0].files[0];
    $(".file-name").html(file ? file.name : "No file chosen");
  });
});
</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="content has-text-centered">
      <p>
        <strong>Invoicebase</strong> is powered by <a href="http://negotiatus.com">Negotiatus</a>.
      </p>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar ">
  <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-item" do %>
      home
    <% end %>
  </div>

  <div class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Upload CSV", csv_import_index_path, class: "navbar-item" %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a href="#" class="navbar-link">More nothing</a>
        <div class="navbar-dropdown">
          <%= link_to "Nothing else", nil, class: "navbar-item" %>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <span class="navbar-item">
        <img src="<%= current_user&.image %>" />
        &nbsp;
        Hi <%= current_user&.first_name %>
        &nbsp;
        <%= link_to "(logout)", destroy_user_session_path %>
      </span>
    </div>
  </div>
</nav>

<% page_color = content_for?(:page_color) ? yield(:page_color) : 'is-primary' %>
<section class="hero <%= page_color %>">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        <%= yield :page_title %>
      </h1>
      <% if content_for :page_subtitle %>
        <h2 class="subtitle">
          <%= yield :page_subtitle %>
        </h2>
      <% end %>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Leadbase</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.0/css/bulma.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.4/lodash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash.present? %>
      <% flash.each do |key, value| %>
        <div class="flash-container <%= flash_class(key) %>">
          <button class="delete is-flash-delete-button"></button>
          <%= value.html_safe %>
        </div>
      <% end %>
      <% flash.clear %>
    <% end %>
    <% if params[:controller] != "static" %>
      <%= render partial: "layouts/navbar" %>
      <div class="container">
        <%= yield %>
      </div>
      <%= render partial: "layouts/footer" %>
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>

app/views/records/index.html.erb
<% provide(:page_title, 'Invoice Reconciliation') %>

<section class="section">
  <form action="" method="get">
    <div class="columns">
      <div class="column">
        <div class="field">
          <div class="control">
            <%= label_tag :filter_start_date, nil, class: 'label' %>
            <%= date_field_tag :filter_start_date, params.fetch(:filter_start_date, nil), class: 'input' %>
          </div>
        </div>
      </div>

      <div class="column">
        <div class="field">
          <div class="control">
            <%= label_tag :filter_end_date, nil, class: 'label' %>
            <%= date_field_tag :filter_end_date, params.fetch(:filter_end_date, nil), class: 'input' %>
          </div>
        </div>
      </div>

      <div class="column">
        <div class="field">
          <%= label_tag :filter_match_status, nil, class: 'label' %>
          <div class="control">
            <div class="select is-fullwidth">
              <%= select_tag 'filter_match_status', options_for_select(['', 'unmatched', 'matched'], params.fetch(:filter_match_status, '')), class: 'is-capitalized' %>
            </div>
          </div>
        </div>
      </div>

      <div class="column">
        <div class="field">
          <%= label_tag :filter_payment_status, nil, class: 'label' %>
          <div class="control">
            <div class="select is-fullwidth">
              <%= select_tag 'filter_payment_status', options_for_select(['', 'unpaid', 'paid'], params.fetch(:filter_payment_status, '')), class: 'is-capitalized' %>
            </div>
          </div>
        </div>
      </div>

      <div class="column">
        <div class="field">
          <%= label_tag :filter_payable_status, nil, class: 'label' %>
          <div class="control">
            <div class="select is-fullwidth">
              <%= select_tag 'filter_payable_status', options_for_select(['', 'unpayable', 'payable'], params.fetch(:filter_payable_status, '')), class: 'is-capitalized' %>
            </div>
          </div>
        </div>
      </div>

      <div class="column is-shrunk">
        <label class="label">&nbsp;</label>
        <input type="submit" value="Filter" class="button is-primary">
      </div>

      <div class="column is-shrunk">
        <label class="label">&nbsp;</label>
        <%= link_to 'Clear', records_path, class: 'button is-light' %>
      </div>
    </form>
  </div>

  <hr>

  <table class="table is-fullwidth">
    <thead>
      <tr>
        <th>External Reference Number</th>
        <th></th>
        <th>Internal Reference Number</th>
        <th>Payable?</th>
        <th>Paid?</th>
      </tr>
    </thead>

    <tbody>
      <% @external_records.each do |record| %>
        <tr>
          <td><%= record.reference_number %></td>
          <td>&raquo;</td>
          <td><%= record.internal_record.reference_number %></td>
          <td><input type="checkbox"> Payable?</td>
          <td><input type="checkbox"> Paid?</td>
        </tr>
      <% end %>

      <% if @external_records.blank? %>
        <tr>
          <td colspan="5"><p class="has-text-centered">No records found for filter</p></td>
        </tr>
      <% end %>
    </tbody>

    <tfoot>
      <tr>
        <th colspan="5" class="has-text-right">
          <input type="submit" value="Save records" class="button is-primary">
        </th>
      </tr>
    </tfoot>
  </table>
</section>